w = "Welcome back!"
CurrT = "The current time is"
CurrD = "The current date is"
Morning = "Hey,Good Morning. Have a nice day!"
Afternoon = "Hey, Good Afternoon. Have a Healthy meal!"
Evening = "Hey, Good Evening. Don't forget to go for a walk"
Night = "Good Night, Sweet dreams"
Welcome = "Hi I'm Baymax your virtual partner, How can I help you?"
NotRecognize = "Can't get you, repeat it again please"
SearchingPedia = "I'm, Working on it please wait!!"
# UserCmd's
BaymaxTime = "what's the time"
BaymaxDate = "today's date please"
BaymaxOff = "shutdown"
BaymaxPedia = "Baymax"